const UPSTREAM = "https://deep33.c-33.blitz.cloud";
const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-deep33-session-id, x-request-id, x-idempotency-key","Access-Control-Allow-Methods":"GET,POST,PUT,OPTIONS"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}});
async function fetchUpstream(path:string,init:RequestInit={}){const headers=new Headers(init.headers||{});headers.delete("Authorization");headers.delete("apikey");headers.delete("x-client-info");return fetch(UPSTREAM+path,{...init,headers,redirect:"follow"});}
async function searchWeb(query:string){const q=query.trim();if(!q)return {ok:false,error:"SEARCH_QUERY_REQUIRED",results:[]};const res=await fetch("https://html.duckduckgo.com/html/?q="+encodeURIComponent(q),{headers:{"User-Agent":"DEEP33/1.0"}});if(!res.ok)return {ok:false,error:"SEARCH_HTTP_"+res.status,results:[]};const html=await res.text();const results:Array<{title:string;url:string;snippet:string}>=[];const blocks=html.split('class="result results_links results_links_deep"').slice(1);const clean=(v:string)=>v.replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,"<").replace(/&gt;/g,">").trim();for(const block of blocks.slice(0,5)){const a=block.match(/class="result__a"[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const s=block.match(/class="result__snippet"[^>]*>([\s\S]*?)<\/a>/i)||block.match(/class="result__snippet"[^>]*>([\s\S]*?)<\/div>/i);results.push({title:clean(a[2]),url:a[1],snippet:clean(s?.[1]||"")});}return {ok:results.length>0,engine:"DuckDuckGo",results};}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const url=new URL(req.url);const path=url.pathname.replace(/^\/functions\/v1\/deep33-proxy/,"")||"/";
if(path==="/v1/connectivity/audit"&&req.method==="GET"){const started=performance.now();let upstream:Record<string,unknown>={health:false,ready:false};try{const [h,r]=await Promise.all([fetchUpstream("/health"),fetchUpstream("/ready")]);upstream.health=h.ok;upstream.health_status=h.status;upstream.ready=r.ok;upstream.ready_status=r.status;}catch(e){upstream.error=e instanceof Error?e.message:String(e);}let search:Record<string,unknown>;try{search=await searchWeb("DEEP33 internet");}catch(e){search={ok:false,error:e instanceof Error?e.message:String(e),results:[]};}return json({status:upstream.health===true&&search.ok===true?"PASS":"FAIL",edge:"PASS",internet:search.ok===true?"PASS":"FAIL",search,upstream,latency_ms:Math.round(performance.now()-started),timestamp:new Date().toISOString()});}
if(path==="/v1/search"&&req.method==="GET"){try{return json(await searchWeb(url.searchParams.get("q")||url.searchParams.get("query")||""));}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e),results:[]},502);}}
if(path.startsWith("/v1/")||path==="/health"||path==="/ready"||path==="/metrics"){try{const body=req.method==="GET"||req.method==="HEAD"?undefined:await req.arrayBuffer();const headers=new Headers();for(const name of ["content-type","accept","x-deep33-session-id","x-request-id","x-idempotency-key"]){const v=req.headers.get(name);if(v)headers.set(name,v);}const res=await fetchUpstream(path+url.search,{method:req.method,headers,body});const out=new Headers(cors);for(const name of ["content-type","cache-control","x-request-id"]){const v=res.headers.get(name);if(v)out.set(name,v);}return new Response(res.body,{status:res.status,headers:out});}catch(e){return json({detail:"DEEP33_UPSTREAM_UNAVAILABLE",error:e instanceof Error?e.message:String(e)},502);}}
return json({status:"PASS",service:"DEEP33 Internet Edge",path,timestamp:new Date().toISOString()});});