-- DEEP33 memory and idempotency foundation.
-- The production database already contains these objects; IF NOT EXISTS keeps
-- this migration safe and makes a clean environment reproducible.

create table if not exists public.deep33_sessions (
  session_id text primary key,
  personality text not null default 'NEUTRO',
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deep33_messages (
  id bigint generated by default as identity primary key,
  session_id text not null references public.deep33_sessions(session_id) on delete cascade,
  role text not null check (role = any (array['system','user','assistant']::text[])),
  content text not null,
  model text,
  provider text,
  request_id text,
  fingerprint text not null,
  created_at timestamptz not null default now(),
  unique (session_id, fingerprint)
);

create table if not exists public.deep33_memories (
  id bigint generated by default as identity primary key,
  session_id text not null references public.deep33_sessions(session_id) on delete cascade,
  kind text not null check (kind = any (array['preference','explicit','summary','context']::text[])),
  content text not null,
  fingerprint text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, fingerprint)
);

create table if not exists public.ai_idempotency (
  idempotency_key text primary key,
  operation text not null,
  status_code integer not null,
  response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  request_hash text,
  state text not null default 'COMPLETED'
    check (state = any (array['IN_PROGRESS','COMPLETED','FAILED']::text[])),
  lock_token text,
  updated_at timestamptz not null default now()
);

create index if not exists deep33_messages_session_created_idx
  on public.deep33_messages (session_id, created_at desc, id desc);

create index if not exists deep33_memories_session_updated_idx
  on public.deep33_memories (session_id, updated_at desc, id desc);

create index if not exists ai_idempotency_expires_idx
  on public.ai_idempotency (expires_at);

create index if not exists ai_idempotency_updated_at_idx
  on public.ai_idempotency (updated_at);

alter table public.deep33_sessions enable row level security;
alter table public.deep33_messages enable row level security;
alter table public.deep33_memories enable row level security;
alter table public.ai_idempotency enable row level security;

revoke all on table public.deep33_sessions from public, anon, authenticated;
revoke all on table public.deep33_messages from public, anon, authenticated;
revoke all on table public.deep33_memories from public, anon, authenticated;
revoke all on table public.ai_idempotency from public, anon, authenticated;

grant all on table public.deep33_sessions to service_role;
grant all on table public.deep33_messages to service_role;
grant all on table public.deep33_memories to service_role;
grant all on table public.ai_idempotency to service_role;

grant usage, select on sequence public.deep33_messages_id_seq to service_role;
grant usage, select on sequence public.deep33_memories_id_seq to service_role;
