-- DEEP33 response feedback metrics.
create table if not exists public.deep33_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id text not null,
  request_id text not null,
  rating text not null check (rating in ('positive','negative')),
  response_hash text,
  created_at timestamptz not null default now()
);

create index if not exists deep33_feedback_user_created_idx
  on public.deep33_feedback (user_id, created_at desc);

create index if not exists deep33_feedback_session_created_idx
  on public.deep33_feedback (session_id, created_at desc);

alter table public.deep33_feedback enable row level security;
revoke all on table public.deep33_feedback from public, anon, authenticated;
grant insert, select on table public.deep33_feedback to service_role;
grant usage, select on sequence public.deep33_feedback_id_seq to service_role;

-- Defensive cleanup for legacy internal GPS markers from older app versions.
update public.deep33_messages
set content = regexp_replace(
  content,
  '\\[(?:UBICACIÓN|UBICACION) GPS ACTUAL[^\\]]*\\]',
  '[contexto local eliminado por privacidad]',
  'gi'
)
where content ~* '\\[(?:UBICACIÓN|UBICACION) GPS ACTUAL[^\\]]*\\]';

update public.deep33_memories
set content = regexp_replace(
  content,
  '\\[(?:UBICACIÓN|UBICACION) GPS ACTUAL[^\\]]*\\]',
  '[contexto local eliminado por privacidad]',
  'gi'
)
where content ~* '\\[(?:UBICACIÓN|UBICACION) GPS ACTUAL[^\\]]*\\]';
