create table if not exists public.deep33_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  session_id text not null,
  response_hash text not null,
  rating text not null check (rating in ('useful', 'not_useful')),
  created_at timestamptz not null default now()
);

create index if not exists deep33_feedback_user_created_idx
  on public.deep33_feedback (user_id, created_at desc);

alter table public.deep33_feedback enable row level security;
revoke all on table public.deep33_feedback from public, anon, authenticated;
grant all on table public.deep33_feedback to service_role;
